# Generated by Django 3.1.6 on 2021-02-09 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UpInfo',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('mid', models.BigIntegerField()),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('url', models.CharField(blank=True, max_length=255, null=True)),
                ('live_url', models.CharField(blank=True, max_length=255, null=True)),
                ('fssl', models.IntegerField(blank=True, null=True)),
                ('spsl', models.IntegerField(blank=True, null=True)),
                ('ydl', models.IntegerField(blank=True, null=True)),
                ('dzl', models.IntegerField(blank=True, null=True)),
                ('bfl', models.IntegerField(blank=True, null=True)),
                ('yn', models.IntegerField(blank=True, null=True)),
                ('created', models.DateTimeField(blank=True, null=True)),
                ('modified', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'up_info',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('up_name', models.CharField(blank=True, max_length=100, null=True)),
                ('mid', models.BigIntegerField(blank=True, null=True)),
                ('url', models.CharField(blank=True, max_length=255, null=True)),
                ('bfl', models.IntegerField(blank=True, null=True)),
                ('plsl', models.IntegerField(blank=True, null=True)),
                ('dt', models.CharField(blank=True, max_length=255, null=True)),
                ('length', models.CharField(blank=True, max_length=255, null=True)),
                ('dmsl', models.IntegerField(blank=True, null=True)),
                ('tags', models.CharField(blank=True, max_length=255, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('yn', models.IntegerField(blank=True, null=True)),
                ('created', models.DateTimeField(blank=True, null=True)),
                ('modified', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'video',
                'managed': True,
            },
        ),
    ]
