# Generated by Django 3.1.6 on 2021-02-09 03:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='upinfo',
            options={'managed': True},
        ),
    ]
